#spring AI core
spring.ai.model.chat=ollama
spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
spring.ai.ollama.chat.model=qwen2.5:1.5b
spring.ai.ollama.embedding.model=nomic-embed-text
# core
spring.application.name=Backend

# Database
spring.mongodb.uri=${MONGODB_URI}
#hat
spring.ai.vectorstore.mongodb.initialize-schema=false

#Spring security
spring.security.user.name=${SPRING_SECURITY_USER}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
server.port=8081
debug=false
